### PR TITLE
python client

### PR DESCRIPTION
**Pull request by lekoOwO**

### CODE REVIEW

**Comment by seadog007** [comment]
Client should be more user friendly, asking for name and id instead of asking for data (what kind of data?????)
Need more work

**Comment by lekoOwO** [comment]
fixed

**Comment by seadog007** [comment]
The request api endpoint should use hash value, not the original data, and the property name should be `hash` if it is possible.
`request_hash` is too long la.

**Comment by seadog007** [comment]
Parse the result data plz

**Comment by seadog007** [comment]
Also change the format string function to let it run on python2

**Comment by lekoOwO** [comment]
fixed

**Comment by seadog007** [comment]
On python2 螢幕快照 2019-08-19 下午6 26 14

**Comment by lekoOwO** [comment]
try it again

**Pull request merged**
