### PR TITLE
C++ client

### PR DESCRIPTION
**Pull request by lekoOwO**
## Thanks
 - [cpp-httplib](https://github.com/yhirose/cpp-httplib)
 - [SHA-1](http://www.zedwood.com/article/cpp-sha1-function)

## Complie and Run
`sh compile_and_run.sh`

### CODE REVIEW

**Comment by seadog007** [comment]
Don't put the binary on, and run some script for compiling

**Comment by lekoOwO** [comment]
Should be good now

**Review by seadog007 — COMMENTED** [review]
You should really make your own http client

**Comment by oToToT** [comment]
I think you might need to include LICENSE from [cpp-httplib](https://github.com/yhirose/cpp-httplib), or maybe you could use something like libcurl, boost.asio if you don't want to be windows-friendly.

**Comment by lekoOwO** [comment]
Since this repo is also licensed in MIT, I'm not sure if a redeclaration is required...

**Comment by seadog007** [comment]
I think using libcurl is a better choice, it can reduce core code size and people can just download libcurl from their system PM

**Comment by seadog007** [comment]
Please use HTTPS

**Review by seadog007 — CHANGES_REQUESTED** [review]
Use HTTPS

**Pull request merged**
